server:
  port: 8081
  servlet:
    session:
      cookie:
        name: socializing

spring:
  datasource:
    url: jdbc:mysql://localhost/oauth_socializing?createDatabaseIfNotExist=true&useSSL=false
    username: root
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true