spring:
  datasource:
    url: jdbc:mysql://localhost/oauth_movies_rating?createDatabaseIfNotExist=true&useSSL=false
    username: root
    driver-class-name: org.gjt.mm.mysql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  servlet:
    session:
      cookie:
        name: movies
